### PR TITLE
Patch & upgrade docker image

### PR DESCRIPTION
**Pull request by eugengi**
## Description
This branch introduces patches and enhancements to the current `sentiment-api` app. This PR's primary target was to build a smaller Docker image to address the following [TODO](https://github.com/martinoywa/sentiment-api/commit/ebf71b008bd25e0fc6e014bd290014b85583b67a). Additional patches and updates were consequently introduced when working locally with the application.

**Patches & Updates:**
- Update to use a smaller base image: `slim-bullseye`.
- Update from version `py39` to `py312`.
- Annotate source code with [type hints](https://docs.python.org/3/library/typing.html)
- Optimize & upgrade `Dockerfile`.
- Fix docs in `README.md`. 

**Decisions:**
> This section outlines notable considerations for developers.
- The `alpine` base image was unsuitable due to **`C` Library Incompatibility**.
- Torch depends on GNU libraries (`glibc`,) whereas `alpine` ships with a different version of the `C` library (`musl-libc`).
- Leverage a Debian-based Linux distribution that ships with a full set of libraries and tools, including `glibc`: **Bullseye**

**Metrics:**
Despite `alpine` being unsuitable for the app, the updated base image, `slim-bullseye`, achieves the target by reducing the image footprint by over `50%` (similar to `alpine`):
```bash
(sentiment) ➜  sentiment-api git:(master) ✗ docker images
REPOSITORY                       TAG                 IMAGE ID       CREATED         SIZE
sentiment-api                    slim-bullseye       dada256b7f74   3 hours ago     1.14GB
sentiment-api                    slim                22a6c3cb3b59   16 hours ago    1.14GB
sentiment-api                    alpine              e0b207c13c13   2 days ago      1.1GB
sentiment-api                    base                c0e437e4aec5   2 days ago      2.04GB
```

## Testing
Run all tests on source code with the following `make` command: `make tests`
`PASSED                                             [100%]
`

## Additional
**General:**
- [Issues] Alpine incompatibility [issues](https://github.com/search?q=repo%3Apytorch%2Fpytorch+alpine&type=issues).
- [Runtime Error] Specific [issue](https://github.com/pytorch/pytorch/issues/102592) faced when running `alpine` container.
- [Recommendation] Add a `LICENSE` to the repository. @martinoywa 

**Security:**
- [Container Security] Leverage [Synk Advisor](https://snyk.io/advisor/docker) to ensure the base image contains no known [vulnerabilities](https://snyk.io/advisor/docker/python/3.12-slim-bullseye).
- [Dependency Security] Leverage [Snyk SCM](https://docs.snyk.io/integrate-with-snyk/git-repositories-scms-integrations-with-snyk) (Open Source Security) to ensure explicit and transitive dependencies do not contain known vulnerabilities:
```
(sentiment) ➜  sentiment-api git:(master) ✗ snyk test                                                                        
Testing /.../.../.../sentiment-api...

Organization:      apexdev37
Package manager:   pip
Target file:       requirements.txt
Project name:      sentiment-api
Open source:       no
Project path:      /.../.../.../sentiment-api
Licenses:          enabled

✔ Tested 43 dependencies for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
```

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [x] Documentation updated (not only docstrings)
- [x] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [x] Manual testing instructions provided
- [x] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

### CODE REVIEW

**Comment by martinoywa** [comment]
Hello @apexDev37! Thanks for the Quality of Life changes! 😎🙌. I'll review them in full later today. But if there are any more improvements you have in mind you can go ahead and make them.

**Comment by martinoywa** [comment]
Oh! I'll also add you as a contributor if you don't mind that.

**Comment by eugengi** [comment]
Hey @martinoywa, Awesome!
I've recently started tinkering with ML apps in my spare time and this repo was a great starting point🚀
Sure thing! I'll make a push if I spot any potential enhancements.

**Comment by martinoywa** [comment]
LGTM! 🚀

**Pull request merged**
